Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Controllers/AccounttingController.cs
using SGP.HCBBOOK.CloudServer.UI.Models;
using SGP.HCBBOOK.CORE.Busssiness.IService;
using SGP.HCBBOOK.CORE.Busssiness.Models;
using SGP.HCBBOOK.CORE.Busssiness.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SGP.HCBBOOK.CloudServer.UI.Controllers
{
    [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff})]
    public class AccounttingController : Controller
    {
        private IUserService userService;
        public AccounttingController()
        {
            userService = new UserService();
        }
        // GET: Accountting
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff})]
        public ActionResult Index()
        {
            HomeViewModel homeViewModel = new HomeViewModel();
            homeViewModel.userProfileModels = userService.GetAllUser();
            return View(homeViewModel);
        }

        // GET: Accountting
        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff })]
        public ActionResult Detail(string userid)
        {
            return View(userService.GetProfileByUserId(userid));
        }

        // GET: Accountting
        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff })]
        public ActionResult Edit(string userid)
        {
            var user = userService.GetProfileByUserId(userid);
            return View(user);
            //return View(new RegisterUserViewModel
            //{
            //    Address = user.Address,
            //    DateCreate = user.DateCreate,
            //    Email = user.Email,
            //    FirstName = user.FirstName,
            //    IsDelete = user.IsDelete,
            //    IsDisable = user.IsDisable,
            //    LastName = user.LastName,
            //    LogoUrl = user.LogoUrl,
            //    NumberPhone = user.NumberPhone,
            //    Password = "",
            //    UserId = user.UserId
            //});
        }

        // GET: Accountting
        [HttpPost, ValidateAntiForgeryToken]
        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff })]
        public ActionResult Edit(UserProfileModel userProfileModel)
        {
            userService.UpdateProfile(userProfileModel);
            return View(userProfileModel);
        }

        [HttpPost]
        public async Task<JsonResult> UploadAync(string userid)
        {
            try
            {
                foreach (string file in Request.Files)
                {
                    var fileContent = Request.Files[file];
                    if (fileContent != null && fileContent.ContentLength > 0 /*&& fileContent.ContentType == "application/octet-stream"*/)
                    {
                        // get a stream
                        var stream = fileContent.InputStream;
                        // and optionally write the file to disk
                        string fileName = Path.GetFileName(Request.Files[file].FileName);
                        //string typefile = (fileName.Trim().ToLower()).Substring(fileName.Length - 4, 4);
                        string typefile = Path.GetExtension(Request.Files[file].FileName);
                        //if (typefile != ".rom")
                        //{
                        //    return Json("Không phải file Rom.", JsonRequestBehavior.AllowGet);
                        //}
                        string directory = String.Format(@"{0}\{1}", PathUpload.PathUploadLogo, userid.Trim());
                        //string pathDiretory = Server.MapPath(directory);
                        if (!Directory.Exists(directory))
                        {
                            Directory.CreateDirectory(directory);
                        }
                        fileName = String.Format("{0}", fileName);
                        var path = Path.Combine(directory, fileName);
                        if (System.IO.File.Exists(path))
                            System.IO.File.Delete(path);

                        Request.Files[file].SaveAs(path);

                        ///Luw truy vet vao csdl
                        userService.UpdateLogo(userid, String.Format(@"{0}\{1}", userid, fileName));
                        return Json("Lưu thành công!");
                    }
                }
            }
            catch (Exception e)
            {

            }
            return Json("Lưu không thành công!");
        }

        public FileResult Download(string filename)
        {
            var FileVirtualPath = String.Format(@"{0}\{1}", PathUpload.PathUploadLogoVirtual, filename);
            return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        }
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Controllers/DownloadController.cs
using SGP.HCBBOOK.CloudServer.UI.Models;
using SGP.HCBBOOK.CORE.Busssiness.IService;
using SGP.HCBBOOK.CORE.Busssiness.Models;
using SGP.HCBBOOK.CORE.Busssiness.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGP.HCBBOOK.CloudServer.UI.Controllers
{
    [Authorize]
    public class DownloadController : Controller
    {
        private ICheckVersion checkVersion;
        public DownloadController()
        {
            checkVersion = new CheckVersion();
        }
        // GET: Download
        public ActionResult Index()
        {
            return View(checkVersion.GetAllList());
        }

        [AllowAnonymous]
        public ActionResult ReleaseDocs()
        {
            return View(checkVersion.GetAllList());
        }

        //--------------------Checkversion ------------------//

        [AllowAnonymous]
        public JsonResult checkversionSGPMGC()
        {
            //checkversion/UpdateVersionConfig.xml
            try
            {
                var checkversioninfo = checkVersion.CheckVersionSGPMGC();
                
                return Json(new
                {
                    CurrentVersion = checkversioninfo.CurrentVersion,
                    Mandatory = checkversioninfo.Mandatory
                    
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

            }

            return null;
        }
        [AllowAnonymous]
        public JsonResult checkversionSGPMG()
        {
            //checkversion/UpdateVersionConfig.xml
            try
            {
                var checkversioninfo = checkVersion.CheckVersionSGPMG();
                return Json(checkversioninfo, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

            }

            return null;
        }
        [AllowAnonymous]
        public FileResult checkversionSGPMG64()
        {
            try
            {
                var FileVirtualPath = String.Format(@"C:\MENU-GAME-CONTROL\Release Product\SGP MG\Update_Current\64bit\update64bit.rar");
                return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
            }
            catch (Exception ex)
            {

            }

            return null;
        }
        [AllowAnonymous]
        public FileResult checkversionSGPMG32()
        {
            try
            {
                var FileVirtualPath = String.Format(@"C:\MENU-GAME-CONTROL\Release Product\SGP MG\Update_Current\32bit\update32bit.rar");
                return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
            }
            catch (Exception ex)
            {

            }

            return null;
        }
        [AllowAnonymous]
        public FileResult checkversionSGPMGC64()
        {
            try
            {
                var FileVirtualPath = String.Format(@"C:\MENU-GAME-CONTROL\Release Product\SGP MG\Update_Current\64bit\update64bit.rar");
                return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
            }
            catch (Exception ex)
            {

            }

            return null;
        }
        [AllowAnonymous]
        public FileResult checkversionSGPMGC32()
        {
            try
            {
                var FileVirtualPath = String.Format(@"C:\MENU-GAME-CONTROL\Release Product\SGP MG\Update_Current\32bit\update32bit.rar");
                return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
            }
            catch (Exception ex)
            {

            }

            return null;
        }
        //--------------------End checkversion--------------//
        //--------------------Download SGP MG --------------//
        public FileResult SGPMG32()
        {
            try
            {
                var FileVirtualPath = String.Format(@"C:\MENU-GAME-CONTROL\Release Product\SGP MG\Version_Current\32bit\32bit.rar");
                return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
            }
            catch (Exception ex)
            {

            }
            
            return null;
        }
        
        public FileResult SGPMG64()
        {
            try
            {
                var FileVirtualPath = String.Format(@"C:\MENU-GAME-CONTROL\Release Product\SGP MG\Version_Current\64bit\64bit.rar");
                return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
            }
            catch (Exception ex)
            {

            }

            return null;
        }
        //--------------------End-----------------------//
        //--------------------Download SGP MGC -----------------//
        public FileResult SGPMGC32()
        {
            try
            {
                var FileVirtualPath = String.Format(@"C:\MENU-GAME-CONTROL\Release Product\SGP MGC\Version_Current\32bit\32bit.rar");
                return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
            }
            catch (Exception ex)
            {

            }

            return null;
        }

        public FileResult SGPMGC64()
        {
            try
            {
                var FileVirtualPath = String.Format(@"C:\MENU-GAME-CONTROL\Release Product\SGP MGC\Version_Current\64bit\64bit.rar");
                return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
            }
            catch (Exception ex)
            {

            }

            return null;
        }
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Controllers/GameManageController.cs
using SGP.HCBBOOK.CloudServer.UI.Models;
using SGP.HCBBOOK.CORE.Busssiness.IService;
using SGP.HCBBOOK.CORE.Busssiness.Models;
using SGP.HCBBOOK.CORE.Busssiness.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGP.HCBBOOK.CloudServer.UI.Controllers
{
    [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff, RolesSys.Client })]
    public class GameManageController : Controller
    {
        private IGameService gameService;
        private IUserService userService;
        public GameManageController()
        {
            gameService = new GameService();
            userService = new UserService();
        }
        // GET: GameManage
        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff })]
        public ActionResult Index()
        {
            return View(new GameManageViewModel { games= gameService.GetAllGameList() });
        }

        // GET: GameManage
        public ActionResult Detail(string id)
        {
            return View();
        }

        // GET: GameManage
        public ActionResult Edit(string id)
        {
            return View();
        }
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGP.HCBBOOK.CloudServer.UI.Controllers
{
    [Authorize]
    public class HelpController : Controller
    {
        // GET: Help
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/Shared/_PartialMenu.cshtml
<ul class="dropdown-menu">
    <li class="header">NOTIFICATIONS</li>
    <li class="body">
        <ul class="menu">
            <li>
                <a href="javascript:void(0);">
                    <div class="icon-circle bg-light-green">
                        <i class="material-icons">person_add</i>
                    </div>
                    <div class="menu-info">
                        <h4>12 new members joined</h4>
                        <p>
                            <i class="material-icons">access_time</i> 14 mins ago
                        </p>
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <div class="icon-circle bg-cyan">
                        <i class="material-icons">add_shopping_cart</i>
                    </div>
                    <div class="menu-info">
                        <h4>4 sales made</h4>
                        <p>
                            <i class="material-icons">access_time</i> 22 mins ago
                        </p>
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <div class="icon-circle bg-red">
                        <i class="material-icons">delete_forever</i>
                    </div>
                    <div class="menu-info">
                        <h4><b>Nancy Doe</b> deleted account</h4>
                        <p>
                            <i class="material-icons">access_time</i> 3 hours ago
                        </p>
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <div class="icon-circle bg-orange">
                        <i class="material-icons">mode_edit</i>
                    </div>
                    <div class="menu-info">
                        <h4><b>Nancy</b> changed name</h4>
                        <p>
                            <i class="material-icons">access_time</i> 2 hours ago
                        </p>
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <div class="icon-circle bg-blue-grey">
                        <i class="material-icons">comment</i>
                    </div>
                    <div class="menu-info">
                        <h4><b>John</b> commented your post</h4>
                        <p>
                            <i class="material-icons">access_time</i> 4 hours ago
                        </p>
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <div class="icon-circle bg-light-green">
                        <i class="material-icons">cached</i>
                    </div>
                    <div class="menu-info">
                        <h4><b>John</b> updated status</h4>
                        <p>
                            <i class="material-icons">access_time</i> 3 hours ago
                        </p>
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <div class="icon-circle bg-purple">
                        <i class="material-icons">settings</i>
                    </div>
                    <div class="menu-info">
                        <h4>Settings updated</h4>
                        <p>
                            <i class="material-icons">access_time</i> Yesterday
                        </p>
                    </div>
                </a>
            </li>
        </ul>
    </li>
    <li class="footer">
        <a href="javascript:void(0);">View All Notifications</a>
    </li>
</ul>

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/Shared/_PartialMenuSystem.cshtml
@using SGP.HCBBOOK.CORE.Busssiness.IService
@using SGP.HCBBOOK.CORE.Busssiness.Service
@using SGP.HCBBOOK.CORE.Busssiness.Models
@{
    IUserService userService = new UserService();
}
<div class="menu">
    <ul class="list">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active">
            <a href="/">
                <i class="material-icons">home</i>
                <span>Home</span>
            </a>
        </li>
        @*@Html.Partial("~/Views/Shared/_PartialRoleManage.cshtml")*@
        @*<li>
                <a href="javascript:void(0);" name="@item.codePosition" class="menu-toggle">
                    <i class="material-icons">widgets</i>
                    <span id="@item.codeDepartment">@item.nameDepartment</span>
                </a>
                <ul class="ml-menu">
                    <li><a href="@Url.Action(item.codeDepartment,"Department",new {posId = item.codePosition})">Quản lý Account</a></li>
                </ul>
                }
            </li>*@
        <!-- Trợ giúp -->
        <li>
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">widgets</i>
                <span>Quản lý tài khoản</span>
            </a>
            <ul class="ml-menu">
                <li><a href="@Url.Action("index", "Manage")">Thông tin cá nhân</a></li>
                <li><a href="@Url.Action("ChangePassword","Manage")">Đổi mật khẩu</a></li>
                <li><a href="@Url.Action("UpdateMyLogo","Manage")">Cập nhật logo</a></li>
                <li><a href="@Url.Action("MyLicence","LicenceManage")">Bản Quyền của tôi</a></li>
            </ul>
        </li>

        @if (userService.CheckAdminSysRole(userService.GetUserId(User.Identity.Name)))
        {
            <li>
                <a href="@Url.Action("index","Accountting")" class="menu-toggle">
                    <i class="material-icons">widgets</i>
                    <span>Quản lý người dùng</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("index","LicenceManage")" class="menu-toggle">
                    <i class="material-icons">widgets</i>
                    <span>Quản lý key Bản quyền</span>
                </a>
            </li>
        }

        @if (userService.CheckRole(userService.GetUserId(User.Identity.Name), RolesSys.DEV))
        {
            <li>
                <a href="javascript:void(0);" class="menu-toggle">
                    <i class="material-icons">widgets</i>
                    <span>Update Softwares</span>
                </a>
                <ul class="ml-menu">
                    <li><a href="@Url.Action("index","UpdateVersion")">Lịch sử cập nhật</a></li>
                    <li><a href="@Url.Action("AddNewVersion","UpdateVersion")">Tạo bản cập nhật</a></li>
                </ul>
            </li>
        }
        <li>
            <a href="@Url.Action("index","GameManage")" class="menu-toggle">
                <i class="material-icons">widgets</i>
                <span>Quản lý Game</span>
            </a>
        </li>

        <li>
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">widgets</i>
                <span>Quản lý máy Client</span>
            </a>
            <ul class="ml-menu">
                <li><a href="@Url.Action("index", "ClientManage")">Tổng quan</a></li>
                <li><a href="@Url.Action("GetAllListClient", "ClientManage")">Danh sách máy Client</a></li>
                <li><a href="@Url.Action("Subclient","ClientManage")">Quản lý Máy trạm</a></li>
                <li><a href="@Url.Action("ControlMenu","ClientManage")">Control Menu</a></li>
            </ul>
        </li>

        @*@if (!userService.CheckAdminSysRole(User.Identity.Name))
            {

            }*@

        <li>
            <a href="@Url.Action("index","Help")" class="menu-toggle">
                <i class="material-icons">widgets</i>
                <span>Trợ giúp</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("index","Download")" class="menu-toggle">
                <i class="material-icons">widgets</i>
                <span>Download</span>
            </a>
        </li>

        <li>
            <a href="@Url.Action("logoff","Account")" class="menu-toggle">
                <i class="material-icons">widgets</i>
                <span>Đăng xuất</span>
            </a>
        </li>
    </ul>
</div>

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/Shared/_PartialRoleManage.cshtml
@using SGP.HCBBOOK.CORE.Busssiness.IService
@using SGP.HCBBOOK.CORE.Busssiness.Service
@{
    bool checkRoleSys = true;
}

@if (checkRoleSys)
{
    <li>
        <a href="@Url.Action("Index","RolesManage")" class="menu-toggle">
            <i class="material-icons">widgets</i>
            <span>Quản lý quyền</span>
        </a>
    </li>

    <li>
        <a href="@Url.Action("CreateUser","UserManage")" class="menu-toggle">
            <i class="material-icons">widgets</i>
            <span>Tạo Người dùng</span>
        </a>
    </li>

}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/Shared/_PartialUserInfo.cshtml
@using SGP.HCBBOOK.CORE.Busssiness.IService
@using SGP.HCBBOOK.CORE.Busssiness.Service
@using SGP.HCBBOOK.CORE.Busssiness.Models
@{
    IUserService userService = new UserService();
    var user = userService.GetProfile(User.Identity.Name);
}
<div class="user-info">
    <div class="image">
        <img src="@Url.Content(user.LogoUrl!=null?user.LogoUrl:"~/asset/images/company.png")" width="48" height="48" alt="User" />
    </div>
    <div class="info-container">
        <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@String.Format("{0} {1}", user.FirstName, user.LastName)</div>
        <div class="email">@User.Identity.Name</div>
        <div class="btn-group user-helper-dropdown">
            <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
            <ul class="dropdown-menu pull-right">
                <li><a href="javascript:void(0);"><i class="material-icons">person</i>Profile</a></li>
                <li role="seperator" class="divider"></li>
                <li><a href="javascript:void(0);"><i class="material-icons">group</i>Followers</a></li>
                <li><a href="javascript:void(0);"><i class="material-icons">shopping_cart</i>Sales</a></li>
                <li><a href="javascript:void(0);"><i class="material-icons">favorite</i>Likes</a></li>
                <li role="seperator" class="divider"></li>
                <li><a href="@Url.Action("Logoff","Account")"><i class="material-icons">input</i>Sign Out</a></li>
            </ul>
        </div>
    </div>
</div>