Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Controllers/UpdateVersionController.cs
using SGP.HCBBOOK.CORE.Busssiness.IService;
using SGP.HCBBOOK.CORE.Busssiness.Models;
using SGP.HCBBOOK.CORE.Busssiness.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGP.HCBBOOK.CloudServer.UI.Controllers
{
    [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.DEV })]
    public class UpdateVersionController : Controller
    {
        private ICheckVersion checkVersion;
        public UpdateVersionController()
        {
            checkVersion = new CheckVersion();
        }
        // GET: UpdateVersion
        //Danh sach ChangeVersion
        public ActionResult Index()
        {
            return View(checkVersion.GetAllList());
        }

        public ActionResult Detail(int id)
        {
            return View(checkVersion.GetDetail(id));
        }

        public ActionResult Edit(int id)
        {
            return View(checkVersion.GetDetail(id));
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Edit(CheckVersionInfoModel checkVersionInfoModel)
        {
            checkVersionInfoModel.DateChange = DateTime.Now;
            if (checkVersion.ModifiedInfoVersion(checkVersionInfoModel))
            {
                return RedirectToAction("Index");
            }
            return View(checkVersionInfoModel);
        }

        public ActionResult AddNewVersion()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult AddNewVersion(CheckVersionInfoModel checkVersionInfoModel)
        {
            checkVersionInfoModel.DateChange = DateTime.Now;
            checkVersionInfoModel.IsUpdateAvailable = true;
            if (checkVersion.AddNewVersion(checkVersionInfoModel))
            {
                return RedirectToAction("Index");
            }
            return View(checkVersionInfoModel);
        }
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/UpdateVersion/AddNewVersion.cshtml
@{
    ViewBag.Title = "Tạo Bản cập nhật";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SGP.HCBBOOK.CORE.Busssiness.Models.CheckVersionInfoModel
<div class="container-fluid">
    @using (Html.BeginForm("AddNewVersion", "UpdateVersion", FormMethod.Post, new { @id = "wizard_with_validation" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Tạo bản cập nhật mới
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label>Version(X.X.X.X)</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.Version, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1", @required = "" } })
                                        @Html.ValidationMessageFor(model => model.Version, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Checksum</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.Checksum, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1" } })
                                        @Html.ValidationMessageFor(model => model.Checksum, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label>HashingAlgorithm</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.HashingAlgorithm, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1" } })
                                        @Html.ValidationMessageFor(model => model.HashingAlgorithm, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Mandatory(1/0)</label>
                                    <div class="form-line">
                                        @Html.CheckBoxFor(model => model.Mandatory, new { @class = "form-control", @type = "checkbox", @name = "name1" })
                                        @Html.ValidationMessageFor(model => model.Mandatory, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>InstallerArgs</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.InstallerArgs, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1" } })
                                        @Html.ValidationMessageFor(model => model.InstallerArgs, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Softname</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.Softname, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1", @required = "" } })
                                        @Html.ValidationMessageFor(model => model.Softname, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <label>ChangeLogs</label>
                        @Html.TextAreaFor(m => m.ChangeLogs, new { @id = "ckeditor" })
                        <br />
                        <button type="submit" class="btn btn-block btn-lg btn-success waves-effect">SAVE</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>


<!-- #END# CKEditor -->
<!-- Jquery Core Js -->
<script src="~/asset/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="~/asset/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="~/asset/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="~/asset/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="~/asset/plugins/node-waves/waves.js"></script>
<!-- Ckeditor -->
<script src="~/asset/plugins/ckeditor/ckeditor.js"></script>
<!-- TinyMCE -->
<script src="~/asset/plugins/tinymce/tinymce.js"></script>
<!-- Custom Js -->
<script src="~/asset/js/admin.js"></script>
<script src="~/asset/js/pages/forms/editors.js"></script>
<script src="../../js/pages/forms/basic-form-elements.js"></script>
<!-- Demo Js -->
<script src="~/asset/js/demo.js"></script>

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/UpdateVersion/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@model SGP.HCBBOOK.CORE.Busssiness.Models.CheckVersionInfoModel
<div class="container-fluid">

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Chi tiết cập nhật @Model.Version
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <h2 class="card-inside-title">Basic Examples</h2>
                    <div class="row clearfix">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Version(X.X.X.X)</label>
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Version, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1", @readonly = "" } })
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Checksum</label>
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Checksum, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1", @readonly = "" } })
                                </div>
                            </div>

                            <div class="form-group">
                                <label>HashingAlgorithm</label>
                                <div class="form-line">
                                    @Html.EditorFor(model => model.HashingAlgorithm, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1", @readonly = "" } })
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Mandatory(1/0)</label>
                                <div class="form-line">
                                    @Html.CheckBoxFor(model => model.Mandatory, new { @class = "form-control", @type = "checkbox", @name = "name1", @readonly = "" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label>InstallerArgs</label>
                                <div class="form-line">
                                    @Html.EditorFor(model => model.InstallerArgs, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1", @readonly = "" } })
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Softname</label>
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Softname, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1", @readonly = "" } })
                                </div>
                            </div>
                        </div>
                    </div>

                    @Html.TextAreaFor(m => m.ChangeLogs, new { @id = "ckeditor", @readonly = "" })
                    <br />
                    <a href="@Url.Action("Edit","UpdateVersion", new { id = Model.ID})" class="btn btn-block btn-lg btn-success waves-effect">Edit</a>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- #END# CKEditor -->
<!-- Jquery Core Js -->
<script src="~/asset/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="~/asset/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="~/asset/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="~/asset/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="~/asset/plugins/node-waves/waves.js"></script>
<!-- Ckeditor -->
<script src="~/asset/plugins/ckeditor/ckeditor.js"></script>
<!-- TinyMCE -->
<script src="~/asset/plugins/tinymce/tinymce.js"></script>
<!-- Custom Js -->
<script src="~/asset/js/admin.js"></script>
<script src="~/asset/js/pages/forms/editors.js"></script>
<script src="../../js/pages/forms/basic-form-elements.js"></script>
<!-- Demo Js -->
<script src="~/asset/js/demo.js"></script>

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/UpdateVersion/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model SGP.HCBBOOK.CORE.Busssiness.Models.CheckVersionInfoModel
<div class="container-fluid">
    @using (Html.BeginForm("Edit", "UpdateVersion", FormMethod.Post, new { @id = "wizard_with_validation" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Chỉnh Sửa cập nhật @Model.Version
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label>Version(X.X.X.X)</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.Version, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1", @required = "" } })
                                        @Html.ValidationMessageFor(model => model.Version, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Checksum</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.Checksum, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1" } })
                                        @Html.ValidationMessageFor(model => model.Checksum, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label>HashingAlgorithm</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.HashingAlgorithm, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1" } })
                                        @Html.ValidationMessageFor(model => model.HashingAlgorithm, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Mandatory(1/0)</label>
                                    <div class="form-line">
                                        @Html.CheckBoxFor(model => model.Mandatory, new { @class = "form-control", @type = "checkbox", @name = "name1" })
                                        @Html.ValidationMessageFor(model => model.Mandatory, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>InstallerArgs</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.InstallerArgs, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1" } })
                                        @Html.ValidationMessageFor(model => model.InstallerArgs, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Softname</label>
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.Softname, new { htmlAttributes = new { @class = "form-control", @type = "text", @name = "name1", @required = "" } })
                                        @Html.ValidationMessageFor(model => model.Softname, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                        </div>
                        <label>ChangeLogs</label>
                        @Html.TextAreaFor(m => m.ChangeLogs, new { @id = "ckeditor" })
                        <br />
                        <button type="submit" class="btn btn-block btn-lg btn-success waves-effect">SAVE</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>


<!-- #END# CKEditor -->
<!-- Jquery Core Js -->
<script src="~/asset/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="~/asset/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="~/asset/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="~/asset/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="~/asset/plugins/node-waves/waves.js"></script>
<!-- Ckeditor -->
<script src="~/asset/plugins/ckeditor/ckeditor.js"></script>
<!-- TinyMCE -->
<script src="~/asset/plugins/tinymce/tinymce.js"></script>
<!-- Custom Js -->
<script src="~/asset/js/admin.js"></script>
<script src="~/asset/js/pages/forms/editors.js"></script>
<script src="../../js/pages/forms/basic-form-elements.js"></script>
<!-- Demo Js -->
<script src="~/asset/js/demo.js"></script>

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/UpdateVersion/Index.cshtml
@{
    ViewBag.Title = "Danh sách thay đổi version";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<SGP.HCBBOOK.CORE.Busssiness.Models.CheckVersionInfoModel>


<!-- Exportable Table -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Danh sách Key Bản quyền
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="javascript:void(0);">Action</a></li>
                            <li><a href="javascript:void(0);">Another action</a></li>
                            <li><a href="javascript:void(0);">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Version</th>
                                <th>Trạng thái</th>
                                <th>Mandatory</th>
                                <th>InstallerArgs</th>
                                <th>Checksum</th>
                                <th>HashingAlgorithm</th>
                                <th>SoftName</th>
                                <th>Người cập nhật</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>STT</th>
                                <th>Version</th>
                                <th>Trạng thái</th>
                                <th>Mandatory</th>
                                <th>InstallerArgs</th>
                                <th>Checksum</th>
                                <th>HashingAlgorithm</th>
                                <th>SoftName</th>
                                <th>Người cập nhật</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @{int stt = 0; }
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@(++stt)</td>
                                    <td><a href="@Url.Action("Detail", "UpdateVersion", new { id = item.ID })">@item.Version</a></td>
                                    @if (item.IsUpdateAvailable)
                                    {
                                        <td class="bg-green">Có sẵn</td>
                                    }
                                    else
                                    {
                                        <td class="bg-pink">Phiên bản củ</td>
                                    }
                                    <td>@item.Mandatory</td>
                                    <td>@item.InstallerArgs</td>
                                    <td>@item.Checksum</td>
                                    <td>@item.HashingAlgorithm</td>
                                    <td>@item.Softname</td>
                                    <td>@item.DateChange</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- #END# Exportable Table -->
<!-- Jquery Core Js -->
<script src="~/asset/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="~/asset/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="~/asset/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="~/asset/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="~/asset/plugins/node-waves/waves.js"></script>
<!-- Jquery DataTable Plugin Js -->
<script src="~/asset/plugins/jquery-datatable/jquery.dataTables.js"></script>
<script src="~/asset/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
<!-- Custom Js -->
<script src="~/asset/js/admin.js"></script>
<script src="~/asset/js/pages/tables/jquery-datatable.js"></script>
<!-- Demo Js -->
<script src="~/asset/js/demo.js"></script>