Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Models/DetailClientViewModel.cs
using SGP.HCBBOOK.CORE.Busssiness.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SGP.HCBBOOK.CloudServer.UI.Models
{
    public class DetailClientViewModel
    {
        public IList<LicenceDetailModel> licenceDetailModels { get; set; }
        public ComputerMACClientModel computerMACClientModel { get; set; }
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Models/GetAllListClientViewModel.cs
using SGP.HCBBOOK.CORE.Busssiness.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SGP.HCBBOOK.CloudServer.UI.Models
{
    public class GetAllListClientViewModel
    {
        public IList<ComputerMACClientModel> computerMACClientModels { get; set; }
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Models/GetListClientActiveLicenceViewModel.cs
using SGP.HCBBOOK.CORE.Busssiness.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SGP.HCBBOOK.CloudServer.UI.Models
{
    public class GetListClientActiveLicenceViewModel
    {
        public IList<ComputerMACClientModel> computerMACClients { get; set; }
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Models/GetListClientNotActiveLicenceViewModel.cs
using SGP.HCBBOOK.CORE.Busssiness.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SGP.HCBBOOK.CloudServer.UI.Models
{
    public class GetListClientNotActiveLicenceViewModel
    {
        public IList<ComputerMACClientModel> computerMACClients { get; set; }
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Controllers/ClientManageController.cs
using SGP.HCBBOOK.CloudServer.UI.Models;
using SGP.HCBBOOK.CORE.Busssiness.IService;
using SGP.HCBBOOK.CORE.Busssiness.Models;
using SGP.HCBBOOK.CORE.Busssiness.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGP.HCBBOOK.CloudServer.UI.Controllers
{
    [Authorize]
    public class ClientManageController : Controller
    {
        private IComputerMACClientService computerMACClientService;
        private IUserService userService;
        public ClientManageController()
        {
            computerMACClientService = new ComputerMACClientService();
            userService = new UserService();
        }
        // GET: ClientManage
        /// <summary>
        /// Admin, Nha vien: Show danh sach tat ca may client, tro link lien ket xem chi tiet may client
        /// Client: Show danh sach may Client cua nguoi do, dc xem chi tiet may Client, dc chinh sua thong tin neu co
        /// </summary>
        /// <returns></returns>
        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff, RolesSys.Client })]
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Xem chi tiet thong tin may Client: danh sach may SubClient cua no,
        /// dang dung Lincence key nao, 
        /// go bo liecence key nay, 
        /// thay doi lincence key khac
        /// Cho phep Chinh sua
        /// </summary>
        /// <param name="clientId"></param>
        /// <returns></returns>
        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff, RolesSys.Client })]
        public ActionResult DetailClient(string clientId)
        {
            return View();
        }

        /// <summary>
        /// Admin, Staff: Xem danh sach tat ca may Sub Client
        /// </summary>
        /// <returns></returns>
        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff, RolesSys.Client })]
        public ActionResult Subclient()
        {
            return View();
        }
        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Client })]
        public ActionResult ControlMenu()
        {
            return View();
        }

        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff, RolesSys.Client })]
        public ActionResult GetAllListClient()
        {
            var list = computerMACClientService.GetAllListClient();
            return View(new GetAllListClientViewModel { computerMACClientModels = list});
        }

        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff, RolesSys.Client })]
        public ActionResult GetAllListSubClient()
        {
            var list = computerMACClientService.GetAllListSubClient();
            return View(new GetAllListSubClientViewModel { computerSubClientModels = list });
        }

        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff, RolesSys.Client })]
        public ActionResult GetListClientNotActiveLicence()
        {
            IList<ComputerMACClientModel> computerMACClients = new List<ComputerMACClientModel>();
            var listClient = computerMACClientService.GetAllListClient();

            if (listClient != null)
            {
                foreach (var item in listClient)
                {
                    if (item.licenceLives.Where(m => m.IsLive == false).Count() > 0)
                        computerMACClients.Add(item);
                }
            }
            string userid = userService.GetUserId(User.Identity.Name);
            if (userService.CheckAdminSysRole(User.Identity.Name,RolesSys.Client))
            {

                computerMACClients = computerMACClients.Where(m => m.UserId == userid).ToList();
            }
            return View(new GetListClientNotActiveLicenceViewModel { computerMACClients = computerMACClients });
        }

        [AuthorizeSGP.AuthorizeSGP(RolesList = new string[] { RolesSys.Admin, RolesSys.Staff, RolesSys.Client })]
        public ActionResult GetListClientActiveLicence()
        {
            IList<ComputerMACClientModel> computerMACClients = new List<ComputerMACClientModel>();
            var listClient = computerMACClientService.GetAllListClient();

            if (listClient != null)
            {
                foreach (var item in listClient)
                {
                    if (item.licenceLives.Where(m => m.IsLive == true && m.IsActive == true).Count() > 0)
                        computerMACClients.Add(item);
                }
            }
            string userid = userService.GetUserId(User.Identity.Name);
            if (userService.CheckAdminSysRole(User.Identity.Name, RolesSys.Client))
            {

                computerMACClients = computerMACClients.Where(m => m.UserId == userid).ToList();
            }
            return View(new GetListClientActiveLicenceViewModel { computerMACClients = computerMACClients });
        }
        
    }
}

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/ClientManage/DetailClient.cshtml
@model SGP.HCBBOOK.CloudServer.UI.Models.DetailClientViewModel
@{
    ViewBag.Title = "DetailClient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("~/Views/ClientManage/_PartialListLicenceActived.cshtml", Model.computerMACClientModel)

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/ClientManage/GetAllListClient.cshtml
@model SGP.HCBBOOK.CloudServer.UI.Models.GetAllListClientViewModel
@{
    ViewBag.Title = "Danh sách máy Client";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container-fluid">
    @Html.Partial("~/Views/ClientManage/_PartialHeaderComputerClient.cshtml")
    @Html.Partial("~/Views/ClientManage/_PartialListClientTable.cshtml", Model.computerMACClientModels)
</div>

<!-- Jquery Core Js -->
<script src="~/asset/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="~/asset/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="~/asset/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="~/asset/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="~/asset/plugins/node-waves/waves.js"></script>
<!-- Jquery DataTable Plugin Js -->
<script src="~/asset/plugins/jquery-datatable/jquery.dataTables.js"></script>
<script src="~/asset/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
<!-- Custom Js -->
<script src="~/asset/js/admin.js"></script>
<script src="~/asset/js/pages/tables/jquery-datatable.js"></script>
<!-- Demo Js -->
<script src="~/asset/js/demo.js"></script>

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/ClientManage/GetListClientActiveLicence.cshtml
@model SGP.HCBBOOK.CloudServer.UI.Models.GetListClientActiveLicenceViewModel
@{
    ViewBag.Title = "Danh sách máy Client đã kích hoạt bản quyền";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    @Html.Partial("~/Views/ClientManage/_PartialHeaderComputerClient.cshtml")
    @Html.Partial("~/Views/ClientManage/_PartialListClientTable.cshtml", Model.computerMACClients)
</div>

<!-- Jquery Core Js -->
<script src="~/asset/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="~/asset/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="~/asset/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="~/asset/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="~/asset/plugins/node-waves/waves.js"></script>
<!-- Jquery DataTable Plugin Js -->
<script src="~/asset/plugins/jquery-datatable/jquery.dataTables.js"></script>
<script src="~/asset/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
<!-- Custom Js -->
<script src="~/asset/js/admin.js"></script>
<script src="~/asset/js/pages/tables/jquery-datatable.js"></script>
<!-- Demo Js -->
<script src="~/asset/js/demo.js"></script>

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/ClientManage/GetListClientNotActiveLicence.cshtml
@model SGP.HCBBOOK.CloudServer.UI.Models.GetListClientNotActiveLicenceViewModel
@{
    ViewBag.Title = "Danh sách máy Client Chưa kích hoạt bản quyền";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    @Html.Partial("~/Views/ClientManage/_PartialHeaderComputerClient.cshtml")
    @Html.Partial("~/Views/ClientManage/_PartialListClientTable.cshtml", Model.computerMACClients)
</div>

<!-- Jquery Core Js -->
<script src="~/asset/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="~/asset/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="~/asset/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="~/asset/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="~/asset/plugins/node-waves/waves.js"></script>
<!-- Jquery DataTable Plugin Js -->
<script src="~/asset/plugins/jquery-datatable/jquery.dataTables.js"></script>
<script src="~/asset/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
<script src="~/asset/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
<!-- Custom Js -->
<script src="~/asset/js/admin.js"></script>
<script src="~/asset/js/pages/tables/jquery-datatable.js"></script>
<!-- Demo Js -->
<script src="~/asset/js/demo.js"></script>

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/ClientManage/_PartialHeaderComputerClient.cshtml
@using SGP.HCBBOOK.CORE.Busssiness.IService
@using SGP.HCBBOOK.CORE.Busssiness.Service
@using SGP.HCBBOOK.CORE.Busssiness.Models

@{
    IComputerMACClientService computerMACClientService = new ComputerMACClientService();
}

<div class="row clearfix">
    <a href="@Url.Action("GetAllListClient","Clientmanage")">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-pink hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">playlist_add_check</i>
                </div>
                <div class="content">
                    <div class="text">Danh sách Client</div>
                    <div class="number count-to" data-from="0" data-to="125" data-speed="15" data-fresh-interval="20">@computerMACClientService.GetAllListClient().Where(m => m.IsDelete == false).Count()</div>
                </div>
            </div>
        </div>
    </a>
    <a href="@Url.Action("GetListClientNotActiveLicence","Clientmanage")">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-pink hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">playlist_add_check</i>
                </div>
                <div class="content">
                    <div class="text">Client chưa kích hoạt bản quyền</div>
                    @{ 
                        var listClients = computerMACClientService.GetAllListClient();
                        int sumlist = listClients.Count();
                        int countlive = 0;
                        foreach (var item in listClients)
                        {
                            if(item.licenceLives!=null)
                            {
                                var tmp = item.licenceLives.Where(m => m.IsLive == true);
                                if(tmp !=null)
                                {
                                    countlive++;
                                }
                            }
                        }
                    }
                    <div class="number count-to" data-from="0" data-to="125" data-speed="15" data-fresh-interval="20">@(sumlist - countlive)</div>
                </div>
            </div>
        </div>
    </a>
    <a href="@Url.Action("GetListClientActiveLicence","Clientmanage")">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-pink hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">playlist_add_check</i>
                </div>
                <div class="content">
                    <div class="text">Client đã kích hoạt bản quyền</div>
                    <div class="number count-to" data-from="0" data-to="125" data-speed="15" data-fresh-interval="20">@countlive</div>
                </div>
            </div>
        </div>
    </a>
    <a href="@Url.Action("GetAllListSubClient","Clientmanage")">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-cyan hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">help</i>
                </div>
                <div class="content">
                    <div class="text">Danh sách Sub Client</div>
                    <div class="number count-to" data-from="0" data-to="257" data-speed="1000" data-fresh-interval="20">@computerMACClientService.GetAllListSubClient().Where(m => m.IsDelete == false).Count()</div>
                </div>
            </div>
        </div>
    </a>
</div>

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/ClientManage/_PartialListClientTable.cshtml
@model IEnumerable<SGP.HCBBOOK.CORE.Busssiness.Models.ComputerMACClientModel>
@using SGP.HCBBOOK.CORE.Busssiness.IService
@using SGP.HCBBOOK.CORE.Busssiness.Service
@using SGP.HCBBOOK.CORE.Busssiness.Models
@{
    IUserService userService = new UserService();
}

<!-- Exportable Table -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Danh sách Máy Client
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="javascript:void(0);">Action</a></li>
                            <li><a href="javascript:void(0);">Another action</a></li>
                            <li><a href="javascript:void(0);">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>MAC Address</th>
                                <th>IP Address</th>
                                <th>Tên máy tính</th>
                                <th>Hệ điều hành</th>
                                <th>Thuộc sở hữu</th>
                                <th>Trạng thái</th>
                                <th>Ngày tham gia</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>STT</th>
                                <th>MAC Address</th>
                                <th>IP Address</th>
                                <th>Tên máy tính</th>
                                <th>Hệ điều hành</th>
                                <th>Thuộc sở hữu</th>
                                <th>Trạng thái</th>
                                <th>Ngày tham gia</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @{int stt = 0; }
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@(++stt)</td>
                                    <td><a href="@Url.Action("DetailClient", "ClientManage",new {clientId = item.MAC})">@(String.Format("{0}", item.MAC))</a></td>
                                    <td>@item.IP</td>
                                    <td>@item.NameComputer</td>
                                    <td>@item.SystemOperator</td>
                                    <td>@userService.GetNameCompanyByUserId(item.UserId)</td>
                                    @if ((bool)!item.IsDisable)
                                    {
                                        <td class="bg-green">Hoạt động</td>
                                    }
                                    else
                                    {
                                        <td class="bg-pink">Bị vô hiệu hóa</td>
                                    }
                                    <td>@item.DateJoin</td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->

Source Code/SGP Server/SGP.HCBBOOK.CloudServer.UI/SGP.HCBBOOK.CloudServer.UI/Views/ClientManage/_PartialListLicenceActived.cshtml
@model SGP.HCBBOOK.CORE.Busssiness.Models.ComputerMACClientModel
@using SGP.HCBBOOK.CORE.Busssiness.IService
@using SGP.HCBBOOK.CORE.Busssiness.Service
@using SGP.HCBBOOK.CORE.Busssiness.Models
@{
    IUserService userService = new UserService();
}

<!-- Exportable Table -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Danh sách Key Bản quyền
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="javascript:void(0);">Action</a></li>
                            <li><a href="javascript:void(0);">Another action</a></li>
                            <li><a href="javascript:void(0);">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>KEY</th>
                                <th>Ngày tạo</th>
                                <th>Người tạo</th>
                                <th>Người sở hữu</th>
                                <th>Ngày dùng cuối</th>
                                <th>Giá trị</th>
                                <th>Trạng thái</th>
                                <td>Cho phép đăng nhập</td>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>STT</th>
                                <th>KEY</th>
                                <th>Ngày tạo</th>
                                <th>Người tạo</th>
                                <th>Người sở hữu</th>
                                <th>Ngày dùng cuối</th>
                                <th>Giá trị</th>
                                <th>Trạng thái</th>
                                <td>Cho phép đăng nhập</td>
                            </tr>
                        </tfoot>
                        <tbody>
                            @{int stt = 0; }
                            @foreach (var item in Model.licenceLives)
                            {
                            <tr>
                                <td>@(++stt)</td>
                                <td><a href="@Url.Action("Detail", "LicenceManage",new {id = item.LicenceId})">@(String.Format("{0}", item.LicenceKey))</a></td>
                                <td>@Model.MAC</td>
                                <td>@Model.NameComputer</td>
                                <td>@Model.SystemOperator</td>
                                @if (item.IsActive == false)
    {
                            <td class="bg-amber">Chưa kích hoạt</td>
}
else if (item.IsActive == false)
{
                            <td class="bg-pink">Bị vô hiệu hóa</td>
}
else
{
                            <td class="bg-green">Đã kích hoạt</td>
}

                                @if (item.IsLive == true)
    {
                            <td class="bg-pink">Đang sử dụng</td>
}
else
{
                            <td class="bg-green">Không được kích hoạt bởi máy nào</td>
}
                            </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->